# Basic provisioning example
- name: Ansible test
  hosts: localhost
  tasks:
  - name: launching AWS instance using Ansible
    ec2:
      key_name: Deepak t2 micro linux
      instance_type: t2.micro
      image: ami-08df646e18b182346
      region: ap-south-1
      wait: yes
      #group: Ansible
      count: 1
      vpc_subnet_id: subnet-0d47c7cc17ec8f644
      assign_public_ip: yes
      aws_access_key: AKIA2RLIAWXT5QNNOKW2
      aws_secret_key: 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
      instance_tags:
                Name: Deepak-ansible