# Basic provisioning example
- name: Ansible test
  hosts: localhost
  tasks:
  - name: launching AWS instance using Ansible
    ec2:
      key_name: Deepak t2 micro linux
      instance_type: t2.micro
      image: ami-
      region: ap-south-1
      wait: yes
      #group: Ansible
      count: 1
      vpc_subnet_id: subnet-
      assign_public_ip: yes
      aws_access_key: 
      aws_secret_key: 
      instance_tags:
                Name: Deepak-ansible
