# Normal loop playbook
- hosts: web
  tasks:
   - copy:
        src: "{{ item }}"
        dest: /tmp
     with_items:
          - /etc/group
          - /etc/shadow
          - /etc/gshadow
          - /etc/passwd  

