kind: ReplicationController
apiVersion: v1
metadata: 
     name: myreplica2
spec:
    replicas: 4
    selector:
        name: Cloudtech
    template:
        metadata:
            name: Cloudtech
            labels:
                name: Cloudtech
        spec:
          containers:
             - name: c00
               image: ubuntu
               command: ["/bin/bash", "-c","while true; do echo deepak singh ; sleep 5; done"]
               ports:
                  - containerPOrt: 80            